### ISSUE TITLE
CompFest 11 - Penyisihan Senior - Penempatan Balon - Tidak ada scorer

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#101]
Pada soal, disebutkan bahwa 
> Apabila ada lebih dari satu jawaban yang valid, keluarkan yang mana saja.

Tetapi, submission [#858546](https://tlx.toki.id/problems/compfest-11-scpc-penyisihan/H/submissions/858546) dan [#858590](https://tlx.toki.id/problems/compfest-11-scpc-penyisihan/H/submissions/858590) lolos di testcase berbeda, padahal program sama, hanya beda di konfigurasi yang dioutput jika ditemukan dua konfigurasi yang valid.

**Comment by fushar** [comment]
Terima kasih atas temuannya. Sudah ditambahkan scorer dari kontes aslinya dan sudah dilakukan rejudge semua pengumpulan.
