### ISSUE TITLE
COMPFEST 11 - Final Junior - Teleportasi Chanek - Gambar Hilang

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#103]
Gambar penjelasan contoh masukan tidak ada.
[Link soal](https://tlx.toki.id/problems/compfest-11-jcpc-final/A).

**Comment by fushar** [comment]
Terima kasih atas laporannya. Sudah diperbaiki oleh panitia yang bersangkutan (@hockyy).
