### ISSUE TITLE
Testcase #22 Robot Penjaga Bermasalah

### ISSUE THREAD

**Issue by ZoroarkDarkrai** [ia-toki/training-gate-issues#17]
Soal : https://training.ia-toki.org/training/curriculums/2/courses/9/chapters/49/problems/217/
Masalah seperti yang dijelaskan pada link berikut masih ada https://www.facebook.com/groups/olimpinfo/permalink/10150620014665961/?comment_id=10150630171700961&comment_tracking=%7B%22tn%22%3A%22R9%22%7D

**Comment by fairuzi10** [comment]
Sudah diperbaiki. Terima kasih laporannya :smiley:
