### ISSUE TITLE
OSN 2012 : Barisan bilangan TC ada yang salah

### ISSUE THREAD

**Issue by thegalang** [ia-toki/training-gate-issues#21]
saya mencoba menggassert constraintnya. sepertinya ada tc dimana Ai>1000000 (ID: 227484)
EDIT: ternyata ada batasan N,K yang tidak sesuai
EDIT2: seperti yang terlihat pada 227496. bahkan menggassert n<=1000000 pun tetap RTE
EDIT3: ternyata masalahnya adalah ada testcase dimana K=N (ID: 227501)

**Comment by athin2008** [comment]
TC pada soal ini telah diperbaiki. Seluruh pengumpulan telah dinilai ulang.
