### ISSUE TITLE
OSN 2011 - Bongkar Sandi : batasan pada testcase tidak tepat

### ISSUE THREAD

**Issue by mamat-rahmat** [ia-toki/training-gate-issues#28]
Pada submission 295239, program dengan worst case 55 interaksi mendapat verdict WA karena > 50 interaksi (padahal batasan di soal 55 interaksi)
![tc](https://user-images.githubusercontent.com/7076754/34978472-ed34443a-fad0-11e7-9675-061fdae1505e.PNG)

**Comment by fairuzi10** [comment]
Sudah diperbaiki. Terima kasih atas laporannya :smiley:
