### ISSUE TITLE
OSN 2011 - Bebek Istimewa : Testcase pada subtask 4 kurang kuat

### ISSUE THREAD

**Issue by mamat-rahmat** [ia-toki/training-gate-issues#29]
Pada submission 296701, solusi bruteforce O(M * 2^M) mendapatkan poin di subtask 4.
Juga pada submission 296763, solusi DP O(M * N) juga mendapatkan poin di subtask 4. Dimana pada solusi tsb array hanya berukuran [2010][1010]. Dapat saya simpulkan bahwa di subtask 4 tidak ada testcase yang N>2010.

**Comment by gyosh** [comment]
Terima kasih atas laporannya.
Namun untuk arsip soal, kasus uji tidak diubah selama tidak ada kesalahan.
Pemerkuatan kasus uji hanya untuk soal pada kursus.
