### ISSUE TITLE
Checker soal Penyisihan Compfest 2011 - Coin Change Deluxe salah?

### ISSUE THREAD

**Issue by dickynovanto1103** [ia-toki/training-gate-issues#33]
Selamat pagi, perkenalkan saya Dicky Novanto, dengan username pada TLX adalah dickynovanto1103. Saya mencoba untuk mengerjakan problem Coin Change Deluxe dalam Arsip Kontes Pemrograman > Compfest > Compfest 2011 > Penyisihan Mahasiswa > Coin Change Deluxe. Saya sudah mengerjakan dan mencoba untuk menjalankan program dan ternyata sudah sama dengan sample tc. Lalu saya coba untuk mensubmit, mendapatkan verdict Wrong Answer dan saya mengecek pada detail submission. Lalu saya melihat bahwa pada sample test data result, verdictnya adalah WA, padahal hasil output local saya sudah sama dengan intended output. Mungkin saya suspect kalau checker output pada judge salah (karena saya juga lihat history submission semua orang yang mensubmit problem itu, ternyata tidak ada yang AC). 

Maka dari itu, saya meminta admin TLX untuk mengecek kasus ini. Terima kasih :D

**Comment by fairuzi10** [comment]
Sudah diperbaiki. Terima kasih laporannya :smiley:
