### ISSUE TITLE
 BNPCHS 2011 - Penyisihan : Kalkulator Rusak

### ISSUE THREAD

**Issue by mamat-rahmat** [ia-toki/training-gate-issues#39]
https://training.ia-toki.org/problemsets/21/problems/106/

Pada contoh keluaran :
```
2
9
62
```
kasus pertama seharusnya 12, seperti dijelaskan di deskripsi soal

**Comment by fairuzi10** [comment]
Sudah diperbaiki. Terima kasih laporannya :smiley:
