### ISSUE TITLE
OSN Informatika 2005 - Faktorial [Deskripsi Soal]

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#41]
![image](https://user-images.githubusercontent.com/38946018/39574959-1649f744-4f03-11e8-9742-5c0007a971fa.png)

Ekspresi
= (2 * 37 * 3 * 52 * 22 * 52) /(3 * 17 * 22 * 13) = (2 * 54 * 37)/(13 * 17)

Seharusnya ada tanda pangkatnya, menjadi
= (2 * 37 * 3 * 5^2 * 2^2 * 5^2) /(3 * 17 * 2^2 * 13) = (2 * 5^4 * 37)/(13 * 17)

Angka 3 dan 2^3 juga hilang dari perkalian faktor di atas. Jadi
= (2 * 37 * 3 * 5^2 * 2^2 * 5^2) /(3 * 17 * 2^2 * 13) = (2^3 * 3 * 5^4 * 37)/(13 * 17)

**Comment by fairuzi10** [comment]
Sudah diperbaiki. Terima kasih laporannya :smiley:
