### ISSUE TITLE
Chapter 10 TLX:  Faktorisasi Prima

### ISSUE THREAD

**Issue by samuelmat19** [ia-toki/training-gate-issues#42]
Untuk soal ini, saya memakai implementasi dengan menggunakan Python. Format sudah saya perhatikan dan jawaban sudah terlihat benar, sudah saya coba juga beberapa kali. Tetapi, pada solusi, hanya menampilkan nilai: 35. Mungkinkah ada kesalahan pada pengecekan sistem?

Kalau admin mau mengecek kode saya secara manual, boleh saya kirimkan via email atau github. Terima kasih sebelumnya.

**Comment by fushar** [comment]
Repositori ini tidak menerima pengecekan kode peserta.

Silakan bertanya spesifik ini pada https://www.facebook.com/groups/olimpinfo/
