### ISSUE TITLE
Course 2 - Chapter 3 - Pendataan Berat Bebek [TC Lemah]

### ISSUE THREAD

**Issue by faishol01** [ia-toki/training-gate-issues#43]
Solusi O(QN) bisa AC. Tolong TC diperkuat. Ide solusi O(QN) sebagai berikut:
1. Mencari sembarang data dengan binary search yang berada di antara range yang dicari. Misal index data yang ditemukan adalah _j_.
2. Melakukan iterasi dari _j_ hingga ke 0 dan menghitung data yang memenuhi syarat. Break iterasi begitu data tidak memenuhi syarat
3. Melakukan iterasi dari _j_ hingga N dan menghitung data yang memenuhi syarat.  Break iterasi begitu data tidak memenuhi syarat

**Comment by faishol01** [comment]
https://pastebin.com/JD4jAeGg

**Comment by hockyy** [comment]
Pruning ajaib

**Comment by gyosh** [comment]
tc sudah diperkuat
