### ISSUE TITLE
Example Testcase - Pasar 16 Ilir

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#46]
Pada problem Pasar 16 Ilir -> https://training.ia-toki.org/problemsets/53/problems/254/, contoh testcase di soal harusnya ada testcase label(0..345), tetapi tidak ada labelnya.

**Comment by gyosh** [comment]
Saya sudah cek dan sample inputnya sama persis dengan
```
0.....6789
2 3
1 2 3
4 5 6
2
0 100
12 12
```

Tau tidak ada labelnya dari mana?

**Comment by dewa251202** [comment]
punya saya kok gak ada ya kak?

**Comment by mamat-rahmat** [comment]
@gyosh Yang dimaksud adalah di deskripsi soalnya. Di deskripsi berbahasa inggris, sampel input tidak mengandung header.

**Comment by dewa251202** [comment]
![image](https://user-images.githubusercontent.com/38946018/42428639-cf680c9a-835e-11e8-99df-4cbf5a8b967a.png)
misalnya pada open subtask, tidak ada string subtask seperti .1...56, ......678

**Comment by dewa251202** [comment]
sudah ada string subtask-nya di soal. Terima kasih :D

**Comment by dewa251202** [comment]
![image](https://user-images.githubusercontent.com/38946018/42428695-34919460-835f-11e8-9152-06dd02c99210.png)
di soal berbahasa inggir tidak ada subtask label seperti : 0....5678, .1..45..8

**Comment by fairuzi10** [comment]
Sudah diperbaiki bersama dengan https://github.com/ia-toki/training-gate-issues/issues/56. Terima kasih laporannya :smiley:
