### ISSUE TITLE
Kelas Pembelajaran Pemrograman, Course 2 : PKD, Chapter 13 : Memenangkan Kompetisi, Problem G : Jawbreaker 5: Cari Optimal [Deskripsi Soal]

### ISSUE THREAD

**Issue by hockyy** [ia-toki/training-gate-issues#47]
Sepertinya harus diterangkan kembali bahwa pemain tidak boleh meruntuhkan hanya 1 bola.
Misalnya pada tc
3 3
4 4 4
1 3 1
2 1 2

Karena permainan belum selesai, jika pemain tidak mengambil bola berlabel 4, pemain bisa saja mengambil bola berlabel 2 dan 3 terlebih dahulu

sehingga akan menjadi
. . .
4 4 4
1 1 1
dan pemain akan mendapat skor 12

Sementara pada solusi saya yang diterima, outputnya 6.

**Comment by gyosh** [comment]
Oke deskripsi sudah ditambahkan. Terima kasih atas laporannya!
