### ISSUE TITLE
Chapter 1A: Masukan dan Keluaran(Transpos Matriks)

### ISSUE THREAD

**Issue by Three-A** [ia-toki/training-gate-issues#48]
Inputan yang diinginkan tidak bisa digunakan pada bahasa pemrograman python 3

**Comment by Three-A** [comment]
![image](https://user-images.githubusercontent.com/13831943/41809013-af28cef6-7710-11e8-822c-c8e1ad9fb8a2.png)

Saya udah masukkan formatnya dengan benar dari inputan sama output sudah sama, tapi masih wrong?

**Comment by mamat-rahmat** [comment]
@Three-A  Coba tuliskan kode programnya disini supaya bisa kita analisa

**Comment by fushar** [comment]
Ditutup karena tidak ada respons.
