### ISSUE TITLE
BNPCHS 2011 - Penyisihan - Problem b

### ISSUE THREAD

**Issue by Dhia01** [ia-toki/training-gate-issues#49]
Cuman kesalahan kecil yang bisa membuat bingung
di contoh keluaran
itu seharusnya 12 bukan 2 :)

**Comment by fairuzi10** [comment]
Sudah diperbaiki bersamaan dengan https://github.com/ia-toki/training-gate-issues/issues/39. Terima kasih laporannya :smiley:
