### ISSUE TITLE
Bebek Untuk Teman

### ISSUE THREAD

**Issue by MichaelElianKevin** [ia-toki/training-gate-issues#50]
Pada soal **Chapter 03: Ekspresi dan Masukan/Keluaran** bagian **D. Bebek Untuk Teman** saya mengerjakan dengan **python 3**. Saya sudah membuat kodenya dan sudah saya coba jalankan hasilnya benar. Tetapi ketika saya submit hasilnya _wrong answer_. Saya sudah mengerjakan dengan **pascal** dengan algoritama, ketika saya submit hasilnya _accepted_. Tetapi. ketika menggunakan **python 3** hasilnya tetap _wrong answer_.

**INI KODE PYTHON 3 SAYA**
`x, y = input().split();`
`print('masing-masing ', int(x)//int(y));`
`print('bersisa ', int(x)%int(y));`

**Comment by mamat-rahmat** [comment]
@MichaelElianKevin fungsi print pada Python 3 otomatis menambahkan spasi antar parameter. Jika diperhatikan lebih jeli, akan ada 2 spasi yang tercetak dari kode tersebut.
