### ISSUE TITLE
Kesalahan Contoh Masukan pada Soal "Pasangan Kota Terjauh" [TOKI Open Contest Mei 2017]

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#54]
Di contoh masukan, nilai Q adalah 1. Padahal format keluaran menyatakan bahwa akan terdapat Q buah bilangan per baris pada keluaran. Tetapi pada contoh keluaran ada 2 bilangan sehingga tidak sesuai dengan contoh masukan.

**Comment by fairuzi10** [comment]
Baris pertama berisi sebuah bilangan bulat yang menyatakan jarak terjauh dari setiap kemungkinan jarak sepasang kota pada awalnya.

Q buah baris berikutnya masing-masing berisi sebuah bilangan bulat yang menyatakan jarak terjauh dari setiap kemungkinan jarak sepasang kota setelah eksperimen ke-i dilakukan.

Berarti ada 1 + Q = 2 baris berisi bilangan bulat. Apakah salah @dewa251202 ?

**Comment by fushar** [comment]
Dianggap tidak ada kesalahan. Silakan balas kembali apabila ternyata ada.
