### ISSUE TITLE
ECEPC 2014 - Huruf Naik Turun - Deskripsi Soal

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#55]
sepertinya soal ini : 
https://training.ia-toki.org/problemsets/14/problems/64/
memiliki deskripsi soal yang salah

karena di situ, fungsi untuk menerjemahkan huruf adalah
f(x) = a + (n + x . (-1)^(x + 1))
tetapi ketika saya mengerjakan soal dengan menggunakan fungsi itu, outputnya tidak sesuai, sedangkan jika saya memakai fungsi
f(x) = a + ((n + x) . (-1)^(x + 1))
saya mendapatkan output yang sesuai

Terima kasih :)

**Comment by fairuzi10** [comment]
Solusimu bukan a + ((n + x) . (-1)^(x + 1)) tetapi a - ((n + x) . (-1)^(x + 1)).

Solusimu bukan membuat f(x), tetapi f invers (perhatikan invers f(x) = a + (n + x . (-1)^(x + 1)) adalah a-((n+x) . (-1)^(x+1)).

Tidak ada masalah pada soal.
