### ISSUE TITLE
Ambiguitas Soal OSN 2016 Hari 1 Soal A "Pasar 16 Ilir" Versi Inggris

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#56]
Pada Versi Inggris, kekurangan keterangan :
" Total uang yang dihabiskan adalah banyaknya uang yang dikeluarkan untuk membeli makanan dikurangi banyaknya uang yang diterima saat mengunjungi kerabatnya. Karena bisa saja memperoleh uang dalam jumlah yang lumayan banyak, total pengeluaran bisa saja kurang dari 0. "
Sehingga menyebabkan ambiguitas pada maksud soal.
Serta pada Sample Testcase (Soal versi Bahasa Inggris), tidak terdapat test case label

**Comment by fairuzi10** [comment]
Sudah diperbaiki. Terima kasih atas laporannya :smiley:
