### ISSUE TITLE
Keslaahan penulisan keluaran soal TOKI DASAR bab 11 Gays penulisan variable

### ISSUE THREAD

**Issue by gladyne** [ia-toki/training-gate-issues#57]

**Comment by gladyne** [comment]
penulisan keluaran masih salah tolong difixkan agar para pemula bisa lebih mengerti https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/14/problems/56/

**Comment by fushar** [comment]
Mohon maaf, kesalahannya apa ya?
