### ISSUE TITLE
Rumus SDS salah

### ISSUE THREAD

**Issue by ZakyHermawan** [ia-toki/training-gate-issues#59]
![Screenshot from 2019-04-22 23-50-03](https://user-images.githubusercontent.com/44158147/56512428-85098880-6559-11e9-829a-5711a37ee751.png)

Gambar diatas merupakan rumus SDS yg ditampilkan pada deskripsi soal, tapi tidak bisa digunakan, jadi saya menggunakan rumus SDS dibawah, dan sudah AC, mohon untuk mengganti gambar rumusnya, agar tidak terjadi kesalahpahaman.

![Screenshot from 2019-04-22 23-53-13](https://user-images.githubusercontent.com/44158147/56512530-d4e84f80-6559-11e9-95c7-7fe516109727.png)

**Comment by fairuzi10** [comment]
Untuk soal apa ya? Bisa diberikan linknya di sini? Terima kasih 😀

**Comment by ZakyHermawan** [comment]
https://training.ia-toki.org/training/curriculums/2/courses/4/chapters/31/problems/137/

Maaf saya lupa mencantumkan linknya

**Comment by fairuzi10** [comment]
Dapat dibuktikan bahwa rumus sds yang diberikan pada soal ekivalen dengan rumus S untuk sampel yang Anda berikan. Submission yang menggunakan rumus yang diberikan juga akan mendapat _accepted_. Silakan dicoba sendiri untuk membuktikannya. Terima kasih atas laporannya!
