### ISSUE TITLE
Kesalahan pada Sample Test Case pada OSN 2016 Hari 1 Soal C (Versi Inggris)

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#60]
Pada versi bahasa Indonesia, sample 2 berupa:

`0..3456789
2 3 3
110`

Sementara pada versi bahasa Inggris, sample 2 berupa :

`..2.456789
3 3 2
101`

**Comment by fairuzi10** [comment]
Kesalahan telah diperbaiki. Terima kasih laporannya! :smile:
