### ISSUE TITLE
Sample output benar, tapi penjelasan format input pada soal berbeda

### ISSUE THREAD

**Issue by ZakyHermawan** [ia-toki/training-gate-issues#61]
Link soal : https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/18/problems/76/

Paragraf kedua kalimat kedua pada format masukan mengatakan bahwa jika  'Jika ukuran matriks semula (R × C) tidak tepat berharga 2^p × 2^p, maka kode-kode pada input menyatakan kuadran homogen pada matriks semula yang telah diperbesar ke ukuran 2^p × 2^p dengan nilai p sekecil mungkin, dengan menambahkan baris-baris berharga 0 di bawah matriks, dan kolom-kolom berharga 0 di sebelah kanan matriks semula.'

Sedangkan pada sample output ukuran matriks tidak diperbesar (sample output 2 & 4).

Saya telah mencoba kemungkinan pertama(ukuran matriks diperbesar ke 2^p * 2^p terdekat, mendapat wrong answer(56), sedangkan saat saya mencoba kemungkinan kedua (ukuran matriks tidak diperbesar) accepted 100%.

**Comment by fairuzi10** [comment]
Matriks yang ditambahkan 0 hanya digunakan untuk mengkodean, sedangkan pada keluaran program yang diminta adalah matriks awal sehingga memiliki ukuran awal RxC.
