### ISSUE TITLE
kesalahan penilaian pada soal ”dua gelang”

### ISSUE THREAD

**Issue by ketler222** [ia-toki/training-gate-issues#63]
![Screenshot_20190624-101718](https://user-images.githubusercontent.com/36614221/59989773-c0642880-966a-11e9-9c4b-67043505d489.jpg)
total nilai dari submission saya pada soal bab programan kompetitif( dasar dasar geometri) yaitu soal dua gelang berjumlah 99 dan dianggap belum selesai

**Comment by fushar** [comment]
Sudah diperbaiki. Terima kasih atas laporannya!
