### ISSUE TITLE
Bug pada page "All Submissions"

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#64]
Dalam "[Versi Lama] Training Gate TOKI Learning Center" dan "Kelas Pembelajaran Pemrograman", pada bagian "All Submssions", jika difilter berdasarkan soal tertentu, kemudian membuka page 2 dan seterusnya, page tersebut kosong / tidak menunjukkan submission apapun.

**Comment by fushar** [comment]
Sudah diperbaiki.
