### ISSUE TITLE
Label "Total Point" tidak terupdate dengan benar

### ISSUE THREAD

**Issue by rama-pang** [ia-toki/training-gate-issues#65]
Pada bagian Arsip Kontes Pemrograman, OSN Informatika 2011 - Sesi 3, label "Total Point" tidak terupdate dengan nilai terbesar.

Sebagai penjelas:

![image](https://user-images.githubusercontent.com/55415829/69930705-044f3980-14f7-11ea-9b92-1a7230b88c0b.png)

![image](https://user-images.githubusercontent.com/55415829/69930715-17620980-14f7-11ea-8fd9-1befa9457010.png)

**Comment by fushar** [comment]
TLX has been migrated, so this issue is not applicable anymore.
