### ISSUE TITLE
Kesalahan kasus uji soal "Jawbreaker IV: Cari Terbesar 2 Langkah"

### ISSUE THREAD

**Issue by zydhanlinnar11** [ia-toki/training-gate-issues#67]
Link soal: https://training.ia-toki.org/training/curriculums/1/courses/11/chapters/52/problems/235/

Dalam soal tertulis "Ingat bahwa Anda hanya boleh memilih bola ketika rangkaian yang mengandung bola tersebut memiliki lebih dari satu bola.". Namun solusi saya yang tetap memilih satu bola malah AC dan solusi yang hanya memilih rangkaian yang memiliki lebih dari satu bola malah WA.
Mohon diperbarui soal/testcasenya.

**Comment by fairuzi10** [comment]
Benar bisa memilih rangkaian yang terdiri hanya dari 1 bola. Mau dihapus saja kalimat ini "Ingat bahwa Anda hanya boleh memilih bola ketika rangkaian yang mengandung bola tersebut memiliki lebih dari satu bola."? Tidak ada keterangan itu juga di Jaw Breaker 2 dan 3.

**Comment by fushar** [comment]
Hmm tapi di Jawbreaker 1 ada batasan seperti itu lho :') Coba dites di Jawbreaker 1 seperti apa test case-nya?

**Comment by fushar** [comment]
Jawbreaker 2 dan 3 seharusnya terdapat batasan seperti itu juga, karena mengikuti deskripsi Jawbreaker 1.

**Comment by fairuzi10** [comment]
Oke, kasus uji sudah diperbaiki ya. Terima kasih atas laporannya! :smile:
