### ISSUE TITLE
Arsip OSN 2014 Hari 2 - Sang Pelompat

### ISSUE THREAD

**Issue by nirvanasm** [ia-toki/training-gate-issues#68]
Runtime error di test 28 batch 6.

Solusi yang sama di submit pada Chapter 13 : Memenangkan Kompetisi - Sang Pelompat mendapatkan accepted.

Apakah terdapat kesalahan testcase?

**Comment by fushar** [comment]
Halo,

Terdapat kesalahan pemasangan soal Sang Pelompat; yang paling benar adalah soal pada Arsip OSN 2014. Soal pada Memenangkan Kompetisi sudah dimodifikasi; mungkin tidak sekuat soal aslinya.

Soal pada Memenangkan Kompetisi sekarang sudah diperbaiki sehingga sama dengan OSN 2014.

(Soal pada OSN 2014 sudah diverifikasi dengan solusi resmi pada OSN tersebut)
