### ISSUE TITLE
Masalah Kasus Uji pada Bundel Soal PCS Joints 2019

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#70]
Sepertinya beberapa soal memiliki kasus uji yang bermasalah seperti pada soal-soal berikut:
1. https://tlx.toki.id/problems/joints-2019-pcs-semifinal/A
2. https://tlx.toki.id/problems/joints-2019-pcs-semifinal/B
3. https://tlx.toki.id/problems/joints-2019-pcs-penyisihan/B

Tolong cek kasus-kasus uji untuk beberapa soal pada bundel soal PCS Joints 2019. Terima kasih.

**Comment by gyosh** [comment]
Baik coba saya periksa

**Comment by gyosh** [comment]
Semuanya sudah diperbaiki, terima kasih atas laporannya
