### ISSUE TITLE
PKD - 6F - Nomor Kandang (Ketidaksesuaian statement dengan testcase)

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#71]
Pada statement soal, tertera :

> Toko tempat Pak Blangkon membeli pelat, menjual pelat 0 hingga pelat N dengan harga yang **berbeda** untuk setiap angka dan memiliki stok yang tidak terbatas.

Tetapi setelah diassert pada [submission ini](https://tlx.toki.id/courses/competitive/chapters/06/submissions/601575), terdapat testcase yang harga platnya non-unik.

**Comment by gyosh** [comment]
Oke, sudah diperbaiki.
Terima kasih atas laporannya @Berted
