### ISSUE TITLE
Akhiran Baris Baru Soal Penyisihan Joints 2019 KPK

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/training-gate-issues#72]
Sepertinya pada soal [ini](https://tlx.toki.id/problems/joints-2019-pcs-penyisihan/B), kasus uji menggunakan akhiran `\r\n`.

Soal tidak bisa diselesaikan apabila hanya menggunakan `\n`.

[Submisi AC](https://tlx.toki.id/problems/joints-2019-pcs-penyisihan/B/submissions/602718)
[Submisi WA](https://tlx.toki.id/problems/joints-2019-pcs-penyisihan/B/submissions/602721)

**Comment by gyosh** [comment]
Ok coba saya cek

**Comment by gyosh** [comment]
Baik sudah diperbaiki. Terima kasih atas laporannya @prabowo02 
Kontribusi Anda memajukan Indonesia.
