### ISSUE TITLE
PKD - 9D - Jalan Tol Menuju Roma [Testcase kurang kuat]

### ISSUE THREAD

**Issue by Berted** [ia-toki/training-gate-issues#73]
[Code ini](https://ideone.com/ZZQRNB) mendapatkan verdict AC, tetapi seharusnya WA.

[Beberapa testcase](https://pastebin.com/fe0gp7rr) yang membuat code ini WA.

**Comment by gyosh** [comment]
ketiga kasus uji baru sudah ditambahkan, terima kasih atas laporannya!
