### ISSUE TITLE
CompFest X - Penyisihan CPC Junior — Problem E [Ambiguitas Deskripsi Soal]

### ISSUE THREAD

**Issue by rama-pang** [ia-toki/training-gate-issues#74]
Ketentuan "Apabila Pak Chanek naik pesawat ke kota i, maka kota i harus dikunjungi" kurang jelas dalam deskripsi soal.

**Comment by gyosh** [comment]
Deskripsi soal sudah diperjelas. Terima kasih atas laporannya.
