### ISSUE TITLE
OSN 2010 - Missile: Testcase tidak sesuai deskripsi soal.

### ISSUE THREAD

**Issue by juancarlovieri** [ia-toki/training-gate-issues#75]
Pada soal ini, testcase 2, 4, dan 13 ada rumah dengan nomor duplikat, di deskripsi ada tertulis bahwa tidak ada dua rumah bernomor sama. 
Saya mengetahuinya dengan mencoba mengassert apabila ada nomor rumah yang duplikat. Submisi: https://tlx.toki.id/problems/osn-2010-3/C/submissions/607903

**Comment by gyosh** [comment]
Terima kasih atas laporannya, soal yang umurnya sudah 10 tahun ini sudah diralat.
