### ISSUE TITLE
Pola I dan Statistika Sederahana WA padahal sudah saya pastikan tidak ada baris baru

### ISSUE THREAD

**Issue by ivanoxx** [ia-toki/training-gate-issues#76]
[Pola I.txt](https://github.com/ia-toki/training-gate-issues/files/4607266/Pola.I.txt)
[Statistika Sederhana.txt](https://github.com/ia-toki/training-gate-issues/files/4607267/Statistika.Sederhana.txt)
mohon bantuannya

**Comment by gyosh** [comment]
Silakan bertanya di https://www.facebook.com/groups/olimpinfo/
Ini hanya tempat pelaporan masalah soal atau testcase.
Untuk kedua soal tersebut, tidak ada masalah pada soal atau testcase.

**Comment by ivanoxx** [comment]
ok thx
