### ISSUE TITLE
Kasus Uji Soal Penghancuran Batu

### ISSUE THREAD

**Issue by NicholasPatrick** [ia-toki/training-gate-issues#77]
Kasus Uji dari Soal Penghancuran Batu (Pemrograman Kompetitif Dasar > 08. Struktur Data Dasar > Problems > E) kurang kuat sehingga submisi 343546 mendapatkan verdict AC meskipun program memiliki kompleksitas worst case O(n^2) dan seharusnya mendapatkan verdict TLE. Testcase untuk menggagalkan submisi ini adalah masukan dengan nilai n besar yang nilainya tidak menaik:

100000

10000 10000 10000 10000 10000 10000 10000 10000 10000 10000 99999 99999 99999 ...

**Comment by prabowo02** [comment]
[Problem link](https://tlx.toki.id/courses/competitive/chapters/08/problems/E)

Test case yang disarankan bisa di-generate dengan Python script berikut:
```python
import random
N = 10**5
print(N)
print(*sorted([random.randint(1, 10000) for i in range(N)], reverse=True), sep='\n')
```

Contoh hasil generate:
[batu-in.txt](https://github.com/ia-toki/training-gate-issues/files/5251348/batu-in.txt)
[batu-out.txt](https://github.com/ia-toki/training-gate-issues/files/5251350/batu-out.txt)

**Comment by prabowo02** [comment]
Test case added
