### ISSUE TITLE
Masalah Pada Beberapa Soal

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#78]
Saya ingin melaporkan beberapa soal yang bermasalah

1. https://tlx.toki.id/problems/ideafuse-2014-cp-final/F/submissions/597735
Saat saya submit sebuah program yang hanya mengeluarkan 
`*666 *55 2222 # *7777 *33 22 33 66 8 2 777 0 555 2 4 444 0 7777 2 999 2 0 55 33 7777 2 66 2 1`
Saya mendapatkan verdict WA pada contoh kasus uji, tetapi setelah saya ganti dengan
`*666 *55 2222 # *7777 *33 22 33 66 8 2 777 0 555 2 4 444 0 7777 2 999 2 0 55 33 7777 2 66 2 1 #`
Saya mendapatkan verdict AC pada contoh kasus uji, sepertinya kasus uji resmi juga memiliki masalah yang mirip

2. https://tlx.toki.id/problems/ideafuse-2014-cp-final/C
Pengguna yang berhasil menyelesaikan soal tersebut hanya 19 dari 113 pengguna yang mencoba. Solusi saya adalah mengelurakan hasil dari 1/N * (N - K - 1)/(N - 1). Mungkin solusi saya salah atau deskripsi soal kurang jelas.

3. https://tlx.toki.id/problems/joints-2011-pcs-final/C
Pengguna yang berhasil menyelesaikan soal tersebut hanya 1 dari 50 pengguna yang mencoba. Tapi saya tidak yakin apa masalahnya.

4. https://tlx.toki.id/problems/compfest-7-jcpc-penyisihan/C
Tidak ada yang berhasil menyelesaikan soal tersebut. Saya sudah submit sebuah solusi yang idenya mirip pada link berikut: https://stackoverflow.com/questions/10670379/find-xor-of-all-numbers-in-a-given-range. Bahkan saya mendapatkan verdict WA pada contoh kasus uji, padahal output sudah benar, yaitu `1010`.

**Comment by fushar** [comment]
Hi @dewa251202 terima kasih atas laporannya ya. Tapi boleh minta untuk bikin 1 issue per soal? 😄

**Comment by dewa251202** [comment]
Baik
