### ISSUE TITLE
IDEAFUSE 2014 - Final CP - Problem F (Messages) : Grader Bermasalah

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#79]
https://tlx.toki.id/problems/ideafuse-2014-cp-final/F

Saat saya submit sebuah program yang hanya mengeluarkan
`*666 *55 2222 # *7777 *33 22 33 66 8 2 777 0 555 2 4 444 0 7777 2 999 2 0 55 33 7777 2 66 2 1`
Saya mendapatkan verdict WA pada contoh kasus uji, tetapi setelah saya ganti dengan
`*666 *55 2222 # *7777 *33 22 33 66 8 2 777 0 555 2 4 444 0 7777 2 999 2 0 55 33 7777 2 66 2 1 #`
Saya mendapatkan verdict AC pada contoh kasus uji, sepertinya kasus uji resmi juga memiliki masalah yang mirip

**Comment by prabowo02** [comment]
Ya, output harus selalu diakhiri dengan `#`

Contoh masukan sudah diperbaiki
