### ISSUE TITLE
IDEAFUSE 2014 - Final CP - Problem C (Anda Memilih) : Deskripsi Kurang Jelas

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#80]
https://tlx.toki.id/problems/ideafuse-2014-cp-final/C

Pengguna yang berhasil menyelesaikan soal tersebut hanya 19 dari 113 pengguna yang mencoba. Solusi saya adalah mengelurakan hasil dari 1/N * (N - K - 1)/(N - 1). Mungkin solusi saya salah atau deskripsi soal kurang jelas.

**Comment by prabowo02** [comment]
Sepertinya terdapat ambiguitas pada deskripsi

Jawaban yang benar untuk soal ini adalah:

<details>
1 / (n * (n-k-1))
</details>

**Comment by prabowo02** [comment]
Terdapat kesalahan pada test case jawaban juri

Telah dimintai test case orisinal soal ini dari universitas penyelenggara itu sendiri, dan test cases telah di-update

Jawaban (N - K - 1) / (N(N - 1)) sudah benar
