### ISSUE TITLE
JOINTS 2011 - Final PCS - Problem C (LJKode) : Grader Bermasalah (?)

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#81]
https://tlx.toki.id/problems/joints-2011-pcs-final/C

Pengguna yang berhasil menyelesaikan soal tersebut hanya 1 dari 50 pengguna yang mencoba. Tapi saya tidak yakin apa masalahnya.

**Comment by prabowo02** [comment]
Terdapat kesalahan pada deskripsi

Aturan pada baris keenam seharusnya di deskripsi:
```
6 Z!,.?
```

seharusnya:
```
6 Z.,!?
```

**Comment by prabowo02** [comment]
Sample output fixed

Terima kasih sudah melapor
