### ISSUE TITLE
CompFest7 - Penyisihan CPC Junior - Problem C (XOR A B) : Grader Bermasalah

### ISSUE THREAD

**Issue by dewa251202** [ia-toki/training-gate-issues#82]
https://tlx.toki.id/problems/compfest-7-jcpc-penyisihan/C

Tidak ada yang berhasil menyelesaikan soal tersebut. Saya sudah submit sebuah solusi yang idenya mirip pada link berikut: https://stackoverflow.com/questions/10670379/find-xor-of-all-numbers-in-a-given-range. Bahkan saya mendapatkan verdict WA pada contoh kasus uji, padahal output sudah benar, yaitu 1010.

**Comment by prabowo02** [comment]
Submission [ini](https://tlx.toki.id/problems/compfest-7-jcpc-penyisihan/C/submissions/692457) AC dengan menggunakan akhiran `\r\n`

**Comment by prabowo02** [comment]
Kasus uji telah diperbaiki
