### ISSUE TITLE
Verdict tertulis WA tetapi comment tertulis AC

### ISSUE THREAD

**Issue by ainunns** [ia-toki/training-gate-issues#87]
pada soal https://tlx.toki.id/courses/competitive/chapters/04/problems/H saya mencoba submit dengan solusi : https://tlx.toki.id/courses/competitive/chapters/04/submissions/741686 mendapatkan verdict sample tc 2 dan test case 15 WA tetapi comment AC. berikut screenshot nya

![image](https://user-images.githubusercontent.com/58164571/101015663-527b9a80-359a-11eb-899f-2e11cc61dfb6.png)

**Comment by fushar** [comment]
Terima kasih atas laporannya. Terdapat kesalahan checker. Sudah diperbaiki dan di-regrade ulang.
