### ISSUE TITLE
Bug pada tab / page "Problems'

### ISSUE THREAD

**Issue by ElrondRafsaAdjani** [ia-toki/training-gate-issues#88]
Pada tab / page problems tombol next page ">" maupun previous page "<" tidak dapat berfungsi dan pada bagian bawah menunjukkan "Showing NaN..NaN of 200 results < >"
![bug problems-tlx](https://user-images.githubusercontent.com/59683978/101177126-0738b900-367a-11eb-8789-fc2cc0601ceb.jpg)

**Comment by fushar** [comment]
Terima kasih atas laporannya. Sudah diperbaiki via https://github.com/ia-toki/judgels/commit/2b68ccb6e2841b839f76e88d27f391fd851dd496.
