### ISSUE TITLE
Sample Test Data Memberikan Verdict WA Padahal Jawaban Sudah Sama (TROC #16 — Problem E)

### ISSUE THREAD

**Issue by ryannolly** [ia-toki/training-gate-issues#89]
Link soal 
https://tlx.toki.id/problems/troc-16/E

Link Submission
https://tlx.toki.id/problems/troc-16/E/submissions/743372

Kode saya adalah seperti berikut 
`#include <bits/stdc++.h>

using namespace std;

int bil[100000];

long long fibonaci(long long a, long long b){
	if(b == 0)
		return a;
	return fibonaci(b, a % b);
}

long long lcm(long long i, long long j){
	long long jawaban = bil[i];
	for(int awal = i+1; awal<=j; awal++){
		jawaban = (jawaban * bil[awal])/fibonaci(jawaban, bil[awal]);
	}
	return jawaban;
}

int main(){	  
	int N;
	cin>>N;
	for(int i = 0; i<N; i++){
		cin>>bil[i];
	}
	long long ans = 1;
	for(int i = 0; i<N; i++){
		for(int j = i; j<N; j++){
			ans = ans * lcm(i, j) % 1000000007;
		}
	}
	
	cout<<ans<<endl;
}`

Pada tlx, memberikan verdict wa pada sampel test data padahal jawaban sudah sama. Apakah terdapat kesalahan pada gradernya atau jawaban saya yang kurang tepat? Terima kasih banyak sebelumnya

![image](https://user-images.githubusercontent.com/48079050/101261509-6aa21400-376a-11eb-9881-0e847d6157d6.png)

**Comment by prabowo02** [comment]
Pada C++17, terdapat built-in function yang bernama `lcm` pula, sehingga pemanggilan fungsi `lcm` yang dilakukan program Anda bukan memanggil fungsi `lcm` yang didefinisikan oleh Anda.

coba submit lagi dengan menggunakan C++11

**Comment by ryannolly** [comment]
Baik sudah berhasil. Terima kasih banyak atas bantuannya..
