### ISSUE TITLE
JOINTS 2018 - Semifinal PCS — Problem A : Kesalahan Pada Contoh Masukan

### ISSUE THREAD

**Issue by ainunns** [ia-toki/training-gate-issues#92]
contoh masukan pertama dari soal [ini](https://tlx.toki.id/problems/joints-2018-pcs-semifinal/A), seharusnya output 2, tetapi contoh keluaran pertama 1

**Comment by prabowo02** [comment]
Terima kasih atas laporannya, contoh keluaran sudah diperbaiki
