### ISSUE TITLE
Progress bar doesn't match sum of points

### ISSUE THREAD

**Issue by rama-pang** [ia-toki/training-gate-issues#93]
![image](https://user-images.githubusercontent.com/55415829/104998116-45890c80-5a5d-11eb-97e6-09e3fdb869c4.png)
![image](https://user-images.githubusercontent.com/55415829/104998137-4de14780-5a5d-11eb-8cc4-6ffc456ed47f.png)
The progress bar should be 700pts/7 instead of 600pts/7

**Comment by fushar** [comment]
Can you repost this to https://github.com/ia-toki/judgels?
