### ISSUE TITLE
Testcase Modified Stack kurang kuat

### ISSUE THREAD

**Issue by Nur47-blip** [ia-toki/training-gate-issues#94]
Testcase pada soal https://tlx.toki.id/courses/competitive/chapters/08/problems/C kurang kuat. 

5
add 1 2
adx 5
add 1 1
del 1
del 1

seharusnya keluarannya adalah 
2
3
1
6

Namun program yang mengeluarkan
2
3
1
1

Tetap mendapat AC. Link: https://ideone.com/PCqxAu

**Comment by prabowo02** [comment]
Kasus uji yang disarankan telah ditambahkan
Terima kasih atas laporannya
