### ISSUE TITLE
Link ke game interaktif mati : OSN Informatika 2013 — Problem 1A

### ISSUE THREAD

**Issue by ainunns** [ia-toki/training-gate-issues#95]
[Link](https://tlx.toki.id/problems/osn-2013/1A) 

![image](https://user-images.githubusercontent.com/58164571/106555687-9fef9600-6550-11eb-8be2-0b04476c6a40.png)

**Comment by fushar** [comment]
Terima kasih atas laporannya. Mohon maaf, game-nya belum berhasil kami temukan. Untuk sementara, link-nya dihapus dari teks soal sampai game-nya ditemukan kembali.
