### ISSUE TITLE
Judgement salah pada course pemrograman dasar - perulangan lanjut - problem B

### ISSUE THREAD

**Issue by ElrondRafsaAdjani** [ia-toki/training-gate-issues#97]
pada problem : https://tlx.toki.id/courses/basic/chapters/07/problems/B

solusi https://tlx.toki.id/courses/basic/chapters/07/submissions/789458 mendapatkan AC 100, seharusnya tidak. Pola yang dioutputkan beda

**Comment by fushar** [comment]
Terima kasih atas laporannya. Sudah diperbaiki.
